name: flutter_custom_tabs
description: A Flutter plugin for mobile apps to launch a URL in Custom Tabs/SFSafariViewController.
version: 2.0.0
repository: https://github.com/droibit/flutter_custom_tabs/tree/main/flutter_custom_tabs

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_custom_tabs_platform_interface: ^2.0.0
  flutter_custom_tabs_android: ^2.0.0+1
  flutter_custom_tabs_ios: ^2.0.0
  flutter_custom_tabs_web: ^2.0.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.1
  plugin_platform_interface: ^2.1.5

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_custom_tabs_android
      ios:
        default_package: flutter_custom_tabs_ios
      web:
        default_package: flutter_custom_tabs_web