name: flutter_custom_tabs
description: A Flutter plugin for mobile apps to launch a URL in Custom Tabs/SFSafariViewController.
version: 2.0.0-beta.1
repository: https://github.com/droibit/flutter_custom_tabs/tree/flutter_custom_tabs_2.0/flutter_custom_tabs
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_custom_tabs_platform_interface:
    path: ../flutter_custom_tabs_platform_interface
  flutter_custom_tabs_android: 
    path: ../flutter_custom_tabs_android
  flutter_custom_tabs_ios: 
    path: ../flutter_custom_tabs_ios
  flutter_custom_tabs_web: 
    path: ../flutter_custom_tabs_web
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.1
  plugin_platform_interface: ^2.1.5

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_custom_tabs_android
      ios:
        default_package: flutter_custom_tabs_ios
      web:
        default_package: flutter_custom_tabs_web