name: flutter_custom_tabs_ios
description: iOS platform implementation of flutter_custom_tabs.
version: 2.0.0
repository: https://github.com/droibit/flutter_custom_tabs/tree/main/flutter_custom_tabs_ios

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs_platform_interface: ^2.0.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^14.0.0

flutter:
  plugin:
    implements: flutter_custom_tabs
    platforms:
      ios:
        pluginClass: GDBCustomTabsPlugin
        dartPluginClass: CustomTabsPluginIOS
