name: flutter_custom_tabs_ios
description: iOS platform implementation of flutter_custom_tabs.
version: 2.0.0-beta
repository: https://github.com/droibit/flutter_custom_tabs/tree/flutter_custom_tabs_2.0/flutter_custom_tabs_ios
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs_platform_interface: 
    path: ../flutter_custom_tabs_platform_interface
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_custom_tabs
    platforms:
      ios:
        pluginClass: GDBCustomTabsPlugin
        dartPluginClass: CustomTabsPluginIOS
