name: flutter_custom_tabs_android
description: Android platform implementation of flutter_custom_tabs.
version: 2.0.0-beta.1
repository: https://github.com/droibit/flutter_custom_tabs/tree/flutter_custom_tabs_2.0/flutter_custom_tabs_android

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: flutter_custom_tabs
    platforms:
      android:
        package: com.github.droibit.flutter.plugins.customtabs
        pluginClass: CustomTabsPlugin
        dartPluginClass: CustomTabsPluginAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs_platform_interface: ^2.0.0-beta.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1