name: flutter_custom_tabs_web
description: Web platform implementation of flutter_custom_tabs.
version: 2.1.0
repository: https://github.com/droibit/flutter_custom_tabs/tree/main/flutter_custom_tabs_web

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: flutter_custom_tabs
    platforms:
      web:
        pluginClass: CustomTabsPluginWeb
        fileName: flutter_custom_tabs_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter 
  flutter_custom_tabs_platform_interface: ^2.1.0
  meta: ^1.10.0
  url_launcher_web: ^2.0.19
  url_launcher_platform_interface: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
