name: flutter_custom_tabs_platform_interface
description: A common platform interface for the flutter_custom_tabs plugin.
version: 2.0.0-beta.1
repository: https://github.com/droibit/flutter_custom_tabs/tree/flutter_custom_tabs_2.0/flutter_custom_tabs_platform_interface

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.1