  
name: CI for android implementation package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'flutter_custom_tabs_android/**'      
  pull_request:
    paths:
      - 'flutter_custom_tabs_android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: ./flutter_custom_tabs_android
    - name: Check for any formatting issues in the code
      run: dart format -o none --set-exit-if-changed $(find ./lib ./test -name "*.dart" -not -name "*.*g.dart")
      working-directory: ./flutter_custom_tabs_android
    - name: Statically analyze the Dart code for any errors
      run: flutter analyze .
      working-directory: ./flutter_custom_tabs_android
    - name: Run unit tests
      run: flutter test
      working-directory: ./flutter_custom_tabs_android
    - name: Build example android app
      run: flutter build apk --release
      working-directory: ./flutter_custom_tabs_android/example      