name: CI for iOS implementation package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'flutter_custom_tabs_ios/**'
      - '.github/workflows/ios_implementation_package.yml'
      - '!**.md'
  pull_request:
    paths:
      - 'flutter_custom_tabs_ios/**'
      - '.github/workflows/ios_implementation_package.yml'
      - '!**.md'
env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    # Workaround for Xcode 15.x performance regression.
    # ref. https://bitrise.io/blog/post/xcode-15-performance-regressions
    - name: Install yeetd
      run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &              
    - uses: irgaly/setup-mint@v1
      with:
        mint-directory: ./flutter_custom_tabs_ios
    - name: Get flutter dependencies
      run: flutter pub get
      working-directory: ./flutter_custom_tabs_ios
    - name: Check for any formatting issues in the code
      run: dart format -o none --set-exit-if-changed $(find ./lib ./test -name "*.dart" -not -name "*.*g.dart")
      working-directory: ./flutter_custom_tabs_ios
    - name: Statically analyze the Dart code for any errors
      run: flutter analyze .
      working-directory: ./flutter_custom_tabs_ios
    - name: Statically analyze the Swift code for any errors
      run: make lint
      working-directory: ./flutter_custom_tabs_ios
    - name: Run flutter unit tests
      run: flutter test
      working-directory: ./flutter_custom_tabs_ios
    - name: Build example iOS app
      run: flutter build ios --no-codesign
      working-directory: ./flutter_custom_tabs_ios/example
    - name: Run iOS unit tests
      run: make test
      working-directory: ./flutter_custom_tabs_ios/example  